### ISSUE TITLE
'devman st root' error

### ISSUE THREAD

**Issue by antoinedeschenes** [kronostechnologies/devman#3]
Calling `devman st root` crashes with the following error on Linux:
```
Traceback (most recent call last):
  File "/home/adeschenes/bin/devman", line 445, in <module>
    main()
  File "/home/adeschenes/bin/devman", line 442, in main
    devman.run()
  File "/home/adeschenes/bin/devman", line 395, in run
    self.st()
  File "/home/adeschenes/bin/devman", line 332, in st
    if release_ahead == "0" and stable_ahead == "0":
UnboundLocalError: local variable 'release_ahead' referenced before assignment
```

**Comment by svigneux** [comment]
@antoinedeschenes PR Welcomed as I'm always short on time ;-)
